import { apiGet, apiPost, apiPatch, apiFetch } from './client.js'

export const usersApi = {
  me: () => apiGet('/users/me'),
  updateTimezone: (timezone, offset) => apiPatch('/users/timezone', { timezone, offset }),
  setOffset: (offset) => apiPatch('/users/offset', { offset }),
  daylightSavings: (shift) => apiPatch('/users/daylight-savings', { shift }),
  addNumber: (number, countrycode) => apiPatch('/users/number', { number, countrycode }),
  setSort: (sort) => apiPatch('/users/sort', { sort }),
  setOpenEarly: (open) => apiPatch('/users/open-early', { open }),
  setAutoDelete: (enabled) => apiPatch('/users/auto-delete', { enabled }),
  setVacationMode: (enabled) => apiPatch('/users/vacation-mode', { enabled }),
  setShowCalendar: (enabled) => apiPatch('/users/show-calendar', { enabled }),
  setPopupCheckDone: () => apiPatch('/users/popup-check', {}),
  completeOnboarding: () => apiPatch('/users/onboarding', {}),
  getNotes: () => apiGet('/users/notes'),
  saveNote: (note) => apiPost('/users/notes', note),
  markdownToHtml: (markdown) => apiPost('/users/markdown', { markdown }),
  markWhatsNewSeen: () => apiPatch('/users/whats-new-seen', {}),
  markGrandfatheredNoteSeen: () => apiPatch('/users/grandfathered-note-seen', {}),
  markTrialWelcomeSeen: () => apiPatch('/users/trial-welcome-seen', {}),
  deleteAccount: () => apiFetch('/users/me', { method: 'DELETE' }),
  setupMfa: (enabled, phone) => apiPatch('/users/mfa', { enabled, phone }),
  verifyMfaSetup: (code, phone) => apiPost('/auth/mfa/setup-verify', { code, phone }),
}
